package com.aryan.yt.engine.services.youtube.extractors.kiosk;

import com.aryan.yt.engine.StreamingService;
import com.aryan.yt.engine.downloader.Downloader;
import com.aryan.yt.engine.exceptions.ExtractionException;
import com.aryan.yt.engine.exceptions.ParsingException;
import com.aryan.yt.engine.exceptions.UnsupportedContentInCountryException;
import com.aryan.yt.engine.linkhandler.ListLinkHandler;

import javax.annotation.Nonnull;
import java.io.IOException;

public class YoutubeTrendingMusicExtractor extends YoutubeChartsBaseKioskExtractor {

    public YoutubeTrendingMusicExtractor(final StreamingService streamingService,
                                         final ListLinkHandler linkHandler,
                                         final String kioskId) {
        super(streamingService, linkHandler, kioskId, "TRENDING_VIDEOS");
    }

    @Override
    public void onFetchPage(@Nonnull final Downloader downloader)
            throws IOException, ExtractionException {
        if (!YT_CHARTS_SUPPORTED_COUNTRY_CODES.contains(
                getExtractorContentCountry().getCountryCode())) {
            throw new UnsupportedContentInCountryException(
                    "YouTube Charts doesn't support this country for trending music videos charts");
        }
        super.onFetchPage(downloader);
    }

    @Nonnull
    @Override
    public String getName() throws ParsingException {
        // This is the official YouTube Charts name, even if autogenerated tracks and unofficial
        // contents are returned
        return "Trending Music Videos";
    }
}
